version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    target-branch: "develop"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      astro:
        patterns:
          - "@astrojs/*"
          - "astro*"
      types:
        patterns:
          - "@types/*"
          - "typescript"
      linting:
        patterns:
          - "eslint*"
          - "typescript-eslint"
      formatting:
        patterns:
          - "prettier*"
      pre-commit:
        patterns:
          - "husky"
          - "lint-staged"
